added terraform plan only

diff --git a/.github/workflows/terraform-plan-apply.yml b/.github/workflows/terraform-plan-apply.yml
--- a/.github/workflows/terraform-plan-apply.yml
+++ b/.github/workflows/terraform-plan-apply.yml
@@ -17,13 +17,20 @@ on:
         required: false
         type: string
 
+permissions:
+  id-token: write
+  contents: read
+
 jobs:
   plan:
     name: Validate and plan changes on ${{ inputs.environment }} environment
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      id-token: write
+
+    outputs:
+      review_required: ${{ steps.tf_plan.outputs.review_required }}
+
+    env:
+      ENVIRONMENT: ${{ inputs.environment }}
 
     steps:
       - name: Checkout Main code
@@ -61,17 +68,96 @@ jobs:
         run: terraform validate
 
       - name: Terraform Plan
+        id: tf_plan
         working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
-        run: terraform plan
+        env:
+          ENVIRONMENT: ${{ inputs.environment }}
+        run: |
+          terraform plan -out=tfplan
+
+          terraform show -no-color tfplan > tfplan.txt
+
+          # Parse plan output
+          plan_line=$(grep "Plan:" tfplan.txt || echo "No changes")
+
+          if [[ "$plan_line" == "Plan:"* ]]; then
+            TF_PLAN_ADD=$(echo "$plan_line" | awk '{print $2}')
+            TF_PLAN_CHANGE=$(echo "$plan_line" | awk '{print $5}')
+            TF_PLAN_DESTROY=$(echo "$plan_line" | awk '{print $8}')
+          else
+            TF_PLAN_ADD=0
+            TF_PLAN_CHANGE=0
+            TF_PLAN_DESTROY=0
+          fi
+
+          echo "TF_PLAN_ADD: $TF_PLAN_ADD"
+          echo "TF_PLAN_CHANGE: $TF_PLAN_CHANGE"
+          echo "TF_PLAN_DESTROY: $TF_PLAN_DESTROY"
+
+          # Require review if:
+          # - any resources being added or destroyed
+          # - OR environment is live (always requires review)
+          if (( $TF_PLAN_ADD > 0 || $TF_PLAN_DESTROY > 0 )) || [[ "$ENVIRONMENT" == "live" ]]; then
+            echo "review_required=true" >> $GITHUB_OUTPUT
+            echo "review_required=true"
+          else
+            echo "review_required=false" >> $GITHUB_OUTPUT
+            echo "review_required=false"
+          fi
 
   apply:
     name: Apply changes on ${{ inputs.environment }} environment
     needs: [plan]
+    if: ${{ needs.plan.outputs.review_required == 'true' }}
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      id-token: write
     environment: ${{ inputs.environment }}
+
+    env:
+      ENVIRONMENT: ${{ inputs.environment }}
+
+    steps:
+      - name: Checkout Main code
+        uses: actions/checkout@v4.2.2
+        with:
+          path: ${{ inputs.main-repo }}
+
+      - name: Pull the repo changes done on the previous job
+        working-directory: ${{ inputs.main-repo }}
+        run: git pull
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4.1.0
+        with:
+          role-to-assume: arn:aws:iam::148221445737:role/automation/GitHubRole-opsai
+          aws-region: us-east-1
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3.1.2
+        with:
+          terraform_version: "1.7.0"
+
+      - name: Terraform Init
+        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
+        run: terraform init
+
+      - name: Terraform select workspace
+        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
+        run: |
+          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
+          echo "TF_WORKSPACE=${{ inputs.environment }}" >> $GITHUB_ENV
+
+      - name: Terraform Apply
+        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
+        run: terraform apply --auto-approve
+
+  auto-apply:
+    name: Auto apply changes on ${{ inputs.environment }} environment
+    needs: [plan]
+    if: ${{ needs.plan.outputs.review_required == 'false' }}
+    runs-on: ubuntu-latest
+
+    env:
+      ENVIRONMENT: ${{ inputs.environment }}
 
     steps:
       - name: Checkout Main code
